name: widget-server pipe

on: 
  push: 
    branches:
      - 'main'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, and push image to Amazon ECR
        id: build-image
        run: |
          docker build -t widget-server:v2 
          docker tag widget-server:v2 ${{ secrets.ECR_REGISTRY }}/ftr/widget-server:v2
          docker push ${{ secrets.ECR_REGISTRY }}/ftr/widget-server:v2